# Generated by Django 2.2.1 on 2019-07-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='user.User'),
            preserve_default=False,
        ),
    ]
