# Generated by Django 2.2.1 on 2019-07-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190704_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nights',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
