# Generated by Django 2.2.1 on 2019-07-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accomodation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
