# Generated by Django 2.2.1 on 2019-05-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190521_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_kakao',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
