# Generated by Django 2.2.1 on 2019-05-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190522_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('FACEBOOK', 'FACEBOOK'), ('KAKAO', 'KAKAO'), ('NAVER', 'NAVER')], max_length=20),
        ),
    ]
