# Generated by Django 2.2.1 on 2019-05-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_id_kakao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[(1, 'FACEBOOK'), (2, 'KAKAO')], max_length=30),
        ),
    ]
