# Generated by Django 2.2.1 on 2019-05-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20190522_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.IntegerField(),
        ),
    ]
