# Generated by Django 2.2.1 on 2019-05-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20190522_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.TextField(),
        ),
    ]
