# Generated by Django 2.2.1 on 2019-05-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20190525_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='status',
        ),
    ]
