# Generated by Django 2.2.1 on 2019-05-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_city_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='code',
        ),
        migrations.RemoveField(
            model_name='state',
            name='status',
        ),
    ]
