# Generated by Django 2.2.1 on 2019-05-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20190527_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
